### ISSUE TITLE
mysql dockerへの接続について

### ISSUE THREAD

**Issue by pei0804** [g-hyoga/test-golang-on-docker#1]
https://github.com/misoten-iw-g2/lovechan
上のリポジトリのコードはゴミなので参考にしないでほしいんだけど、Dockerで全て完結している。

version3のDockerから接続するための名前解決をよしなにしてくれてる。
例えば、servicesでmysqlっていう名前で定義した場合、`mysql:3306`といったか形で普通にアクセス出来るようにしてくれている。

```yml
develop:
  dialect: mysql
  user: lovechan
  password: password
  protocol: tcp
  host: mysql
  port: 3306
  database: lovechan
  option: parseTime=true&collation=utf8mb4_general_ci&interpolateParams=true
  dir: migrations
```

```go
type MysqlConfig struct {
	Datasource string `yaml:"datasource"`
	User       string `yaml:"user"`
	Password   string `yaml:"password"`
	Protocol   string `yaml:"protocol"`
	Host       string `yaml:"host"`
	Port       string `yaml:"port"`
	Database   string `yaml:"database"`
	Option     string `yaml:"option"`
}

// Open connets database.
// NOTE: supports mysql only.
func (c *MysqlConfig) Open() (*sqlx.DB, error) {
	return sqlx.Open("mysql",
		fmt.Sprintf("%s:%s@%s(%s:%s)/%s?%s",
			c.User,
			c.Password,
			c.Protocol,
			c.Host,
			c.Port,
			c.Database,
			c.Option,
		))
}
```

```yml

version: '3'
services:
  golang:
    build:
      context: .
      args:
        USER: $USER
        UID: $UID
    image: golang-app
    volumes:
      - ./go:/go
    command: sh ./start.sh
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - phpmyadmin
  mysql: <---------この名前に対してアクセスすれば良い
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=lovechan
        - MYSQL_USER=lovechan
        - MYSQL_PASSWORD=password
    ports:
        - 3306:3306
    volumes:
        - "./mysql:/var/lib/mysql"
    env_file:
      - .env_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql_mode=""
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=password
    ports:
        - 8000:80
    volumes:
        - /sessions
```
